// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UPMSF.Server.Data;

#nullable disable

namespace UPMSF.Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("RegistrationSeq")
                .StartsAt(1000001L);

            modelBuilder.Entity("UPMSF.Server.Data.Applicant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ApplicantType")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationSequence")
                        .HasColumnType("int");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactPersonName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("ProposedInstituteName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RegistrationId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SocietyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("RegistrationId")
                        .IsUnique();

                    b.HasIndex("Phone", "RegistrationId");

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("UPMSF.Server.Data.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("AppliedFor")
                        .HasColumnType("int");

                    b.Property<int>("CouncilId")
                        .HasColumnType("int");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("CourseType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("int");

                    b.Property<bool>("IsShortForm")
                        .HasColumnType("bit");

                    b.Property<int?>("NoOfExistingSeats")
                        .HasColumnType("int");

                    b.Property<int?>("NoOfSeatsApplied")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("ApplicationNumber")
                        .IsUnique();

                    b.HasIndex("CouncilId");

                    b.HasIndex("CourseId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("UPMSF.Server.Data.ApplicationDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("UPMSF.Server.Data.Council", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Councils");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Paramedical Council"
                        });
                });

            modelBuilder.Entity("UPMSF.Server.Data.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CouncilId")
                        .HasColumnType("int");

                    b.Property<int>("CourseType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CouncilId = 1,
                            CourseType = 1,
                            Name = "Diploma in Anaesthesia and Operation Theatre Technology",
                            ShortCode = "D.AOTT"
                        },
                        new
                        {
                            Id = 2,
                            CouncilId = 1,
                            CourseType = 1,
                            Name = "Diploma of Radiotherapy Technology",
                            ShortCode = "D.RT"
                        },
                        new
                        {
                            Id = 3,
                            CouncilId = 1,
                            CourseType = 1,
                            Name = "Diploma of Dialysis Technology",
                            ShortCode = "D.DT"
                        },
                        new
                        {
                            Id = 4,
                            CouncilId = 1,
                            CourseType = 1,
                            Name = "Diploma of Health Information Management",
                            ShortCode = "D.HIM"
                        },
                        new
                        {
                            Id = 5,
                            CouncilId = 1,
                            CourseType = 2,
                            Name = "Bachelor of Medical Laboratory Science",
                            ShortCode = "B.MLS"
                        },
                        new
                        {
                            Id = 6,
                            CouncilId = 1,
                            CourseType = 2,
                            Name = "Bachelor of Emergency Medical Technologist (Paramedic)",
                            ShortCode = "B.EMT"
                        },
                        new
                        {
                            Id = 7,
                            CouncilId = 1,
                            CourseType = 2,
                            Name = "Bachelor of Anaesthesia and Operation Theatre Technology",
                            ShortCode = "B.AOTT"
                        },
                        new
                        {
                            Id = 8,
                            CouncilId = 1,
                            CourseType = 2,
                            Name = "Bachelor of Physiotherapy",
                            ShortCode = "B.PT"
                        },
                        new
                        {
                            Id = 9,
                            CouncilId = 1,
                            CourseType = 2,
                            Name = "Bachelor of Nutrition and Dietetics (Honours)",
                            ShortCode = "B.ND"
                        },
                        new
                        {
                            Id = 10,
                            CouncilId = 1,
                            CourseType = 2,
                            Name = "Bachelor of Optometry",
                            ShortCode = "B.OPTOM"
                        },
                        new
                        {
                            Id = 11,
                            CouncilId = 1,
                            CourseType = 2,
                            Name = "Bachelor of Occupational Therapy",
                            ShortCode = "B.OT"
                        },
                        new
                        {
                            Id = 12,
                            CouncilId = 1,
                            CourseType = 2,
                            Name = "Bachelor of Psychology",
                            ShortCode = "B.Psy"
                        },
                        new
                        {
                            Id = 13,
                            CouncilId = 1,
                            CourseType = 2,
                            Name = "Bachelor of Medical and Psychiatric Social Work",
                            ShortCode = "B.MPSW"
                        },
                        new
                        {
                            Id = 14,
                            CouncilId = 1,
                            CourseType = 2,
                            Name = "Bachelor of Medical Radiology and Imaging Technology",
                            ShortCode = "B.MRIT"
                        },
                        new
                        {
                            Id = 15,
                            CouncilId = 1,
                            CourseType = 2,
                            Name = "Bachelor of Radiation Therapy Technology",
                            ShortCode = "B.RTT"
                        },
                        new
                        {
                            Id = 16,
                            CouncilId = 1,
                            CourseType = 2,
                            Name = "Bachelor of Science in Nuclear Medicine Technology",
                            ShortCode = "B.Sc.NMT"
                        },
                        new
                        {
                            Id = 17,
                            CouncilId = 1,
                            CourseType = 2,
                            Name = "Bachelor of Physician Associates",
                            ShortCode = "B.PA"
                        },
                        new
                        {
                            Id = 18,
                            CouncilId = 1,
                            CourseType = 2,
                            Name = "Bachelor of Dialysis Therapy Technology",
                            ShortCode = "B.DTT"
                        },
                        new
                        {
                            Id = 19,
                            CouncilId = 1,
                            CourseType = 2,
                            Name = "Bachelor of Respiratory Technology",
                            ShortCode = "B.RT"
                        },
                        new
                        {
                            Id = 20,
                            CouncilId = 1,
                            CourseType = 2,
                            Name = "Bachelor of Science in Health Information Management",
                            ShortCode = "B.Sc.HIM"
                        },
                        new
                        {
                            Id = 21,
                            CouncilId = 1,
                            CourseType = 3,
                            Name = "Master of Medical Laboratory Science",
                            ShortCode = "M.MLS"
                        },
                        new
                        {
                            Id = 22,
                            CouncilId = 1,
                            CourseType = 3,
                            Name = "Master of Advanced Care Paramedic",
                            ShortCode = "M.ACP"
                        },
                        new
                        {
                            Id = 23,
                            CouncilId = 1,
                            CourseType = 3,
                            Name = "Master of Anaesthesia and Operation Theatre Technology",
                            ShortCode = "M.AOTT"
                        },
                        new
                        {
                            Id = 24,
                            CouncilId = 1,
                            CourseType = 3,
                            Name = "Master of Physiotherapy",
                            ShortCode = "M.PT"
                        },
                        new
                        {
                            Id = 25,
                            CouncilId = 1,
                            CourseType = 3,
                            Name = "Master of Nutrition and Dietetics (Honours)",
                            ShortCode = "M.ND"
                        },
                        new
                        {
                            Id = 26,
                            CouncilId = 1,
                            CourseType = 3,
                            Name = "Master of Optometry",
                            ShortCode = "M.OPTOM"
                        },
                        new
                        {
                            Id = 27,
                            CouncilId = 1,
                            CourseType = 3,
                            Name = "Master of Occupational Therapy",
                            ShortCode = "M.OT"
                        },
                        new
                        {
                            Id = 28,
                            CouncilId = 1,
                            CourseType = 3,
                            Name = "Master of Medical Social Work / Master of Psychiatric Social Work",
                            ShortCode = "M.MSW/M.PSW"
                        },
                        new
                        {
                            Id = 29,
                            CouncilId = 1,
                            CourseType = 3,
                            Name = "Master of Medical Radiology and Imaging Technology",
                            ShortCode = "M.MRIT"
                        },
                        new
                        {
                            Id = 30,
                            CouncilId = 1,
                            CourseType = 3,
                            Name = "Master of Radiation Therapy Technology",
                            ShortCode = "M.RTT"
                        },
                        new
                        {
                            Id = 31,
                            CouncilId = 1,
                            CourseType = 3,
                            Name = "Master of Science in Nuclear Medicine Technology",
                            ShortCode = "M.Sc.NMT"
                        },
                        new
                        {
                            Id = 32,
                            CouncilId = 1,
                            CourseType = 3,
                            Name = "Master of Science in Medical Physics",
                            ShortCode = "M.Sc. Medical Physics"
                        },
                        new
                        {
                            Id = 33,
                            CouncilId = 1,
                            CourseType = 3,
                            Name = "Post Master Diploma in Radiological/Medical Physics or Advanced Master Degree in Radiological/Medical Physics",
                            ShortCode = "PMD.RMP"
                        },
                        new
                        {
                            Id = 34,
                            CouncilId = 1,
                            CourseType = 3,
                            Name = "Master of Physician Associates",
                            ShortCode = "M.PA"
                        },
                        new
                        {
                            Id = 35,
                            CouncilId = 1,
                            CourseType = 3,
                            Name = "Master of Dialysis Therapy",
                            ShortCode = "M.DT"
                        },
                        new
                        {
                            Id = 36,
                            CouncilId = 1,
                            CourseType = 3,
                            Name = "Master of Respiratory Technology",
                            ShortCode = "M.RT"
                        },
                        new
                        {
                            Id = 37,
                            CouncilId = 1,
                            CourseType = 3,
                            Name = "Master of Science in Health Information Management",
                            ShortCode = "M.Sc.HIM"
                        });
                });

            modelBuilder.Entity("UPMSF.Server.Data.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "AGRA"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ALIGARH"
                        },
                        new
                        {
                            Id = 3,
                            Name = "AMBEDKAR NAGAR"
                        },
                        new
                        {
                            Id = 4,
                            Name = "AMETHI"
                        },
                        new
                        {
                            Id = 5,
                            Name = "AMROHA"
                        },
                        new
                        {
                            Id = 6,
                            Name = "AURAIYA"
                        },
                        new
                        {
                            Id = 7,
                            Name = "AYODHYA"
                        },
                        new
                        {
                            Id = 8,
                            Name = "AZAMGARH"
                        },
                        new
                        {
                            Id = 9,
                            Name = "BAGHPAT"
                        },
                        new
                        {
                            Id = 10,
                            Name = "BAHRAICH"
                        },
                        new
                        {
                            Id = 11,
                            Name = "BALLIA"
                        },
                        new
                        {
                            Id = 12,
                            Name = "BALRAMPUR"
                        },
                        new
                        {
                            Id = 13,
                            Name = "BANDA"
                        },
                        new
                        {
                            Id = 14,
                            Name = "BARABANKI"
                        },
                        new
                        {
                            Id = 15,
                            Name = "BAREILLY"
                        },
                        new
                        {
                            Id = 16,
                            Name = "BASTI"
                        },
                        new
                        {
                            Id = 17,
                            Name = "BHADOHI"
                        },
                        new
                        {
                            Id = 18,
                            Name = "BIJNOR"
                        },
                        new
                        {
                            Id = 19,
                            Name = "BUDAUN"
                        },
                        new
                        {
                            Id = 20,
                            Name = "BULANDSHAHR"
                        },
                        new
                        {
                            Id = 21,
                            Name = "CHANDAULI"
                        },
                        new
                        {
                            Id = 22,
                            Name = "CHITRAKOOT"
                        },
                        new
                        {
                            Id = 23,
                            Name = "DEORIA"
                        },
                        new
                        {
                            Id = 24,
                            Name = "ETAH"
                        },
                        new
                        {
                            Id = 25,
                            Name = "ETAWAH"
                        },
                        new
                        {
                            Id = 26,
                            Name = "FARRUKHABAD"
                        },
                        new
                        {
                            Id = 27,
                            Name = "FATEHPUR"
                        },
                        new
                        {
                            Id = 28,
                            Name = "FIROZABAD"
                        },
                        new
                        {
                            Id = 29,
                            Name = "GAUTAM BUDDHA NAGAR"
                        },
                        new
                        {
                            Id = 30,
                            Name = "GHAZIABAD"
                        },
                        new
                        {
                            Id = 31,
                            Name = "GHAZIPUR"
                        },
                        new
                        {
                            Id = 32,
                            Name = "GONDA"
                        },
                        new
                        {
                            Id = 33,
                            Name = "GORAKHPUR"
                        },
                        new
                        {
                            Id = 34,
                            Name = "HAMIRPUR"
                        },
                        new
                        {
                            Id = 35,
                            Name = "HAPUR"
                        },
                        new
                        {
                            Id = 36,
                            Name = "HARDOI"
                        },
                        new
                        {
                            Id = 37,
                            Name = "HATHRAS"
                        },
                        new
                        {
                            Id = 38,
                            Name = "JALAUN"
                        },
                        new
                        {
                            Id = 39,
                            Name = "JAUNPUR"
                        },
                        new
                        {
                            Id = 40,
                            Name = "JHANSI"
                        },
                        new
                        {
                            Id = 41,
                            Name = "KANNAUJ"
                        },
                        new
                        {
                            Id = 42,
                            Name = "KANPUR DEHAT"
                        },
                        new
                        {
                            Id = 43,
                            Name = "KANPUR NAGAR"
                        },
                        new
                        {
                            Id = 44,
                            Name = "KASGANJ"
                        },
                        new
                        {
                            Id = 45,
                            Name = "KAUSHAMBI"
                        },
                        new
                        {
                            Id = 46,
                            Name = "KHERI"
                        },
                        new
                        {
                            Id = 47,
                            Name = "KUSHINAGAR"
                        },
                        new
                        {
                            Id = 48,
                            Name = "LALITPUR"
                        },
                        new
                        {
                            Id = 49,
                            Name = "LUCKNOW"
                        },
                        new
                        {
                            Id = 50,
                            Name = "MAHARAJGANJ"
                        },
                        new
                        {
                            Id = 51,
                            Name = "MAHOBA"
                        },
                        new
                        {
                            Id = 52,
                            Name = "MAINPURI"
                        },
                        new
                        {
                            Id = 53,
                            Name = "MATHURA"
                        },
                        new
                        {
                            Id = 54,
                            Name = "MAU"
                        },
                        new
                        {
                            Id = 55,
                            Name = "MEERUT"
                        },
                        new
                        {
                            Id = 56,
                            Name = "MIRZAPUR"
                        },
                        new
                        {
                            Id = 57,
                            Name = "MORADABAD"
                        },
                        new
                        {
                            Id = 58,
                            Name = "MUZAFFARNAGAR"
                        },
                        new
                        {
                            Id = 59,
                            Name = "PILIBHIT"
                        },
                        new
                        {
                            Id = 60,
                            Name = "PRATAPGARH"
                        },
                        new
                        {
                            Id = 61,
                            Name = "PRAYAGRAJ"
                        },
                        new
                        {
                            Id = 62,
                            Name = "RAE BARELI"
                        },
                        new
                        {
                            Id = 63,
                            Name = "RAMPUR"
                        },
                        new
                        {
                            Id = 64,
                            Name = "SAHARANPUR"
                        },
                        new
                        {
                            Id = 65,
                            Name = "SAMBHAL"
                        },
                        new
                        {
                            Id = 66,
                            Name = "SANT KABIR NAGAR"
                        },
                        new
                        {
                            Id = 67,
                            Name = "SHAHJAHANPUR"
                        },
                        new
                        {
                            Id = 68,
                            Name = "SHAMLI"
                        },
                        new
                        {
                            Id = 69,
                            Name = "SHRAVASTI"
                        },
                        new
                        {
                            Id = 70,
                            Name = "SIDDHARTHNAGAR"
                        },
                        new
                        {
                            Id = 71,
                            Name = "SITAPUR"
                        },
                        new
                        {
                            Id = 72,
                            Name = "SONBHADRA"
                        },
                        new
                        {
                            Id = 73,
                            Name = "SULTANPUR"
                        },
                        new
                        {
                            Id = 74,
                            Name = "UNNAO"
                        },
                        new
                        {
                            Id = 75,
                            Name = "VARANASI"
                        });
                });

            modelBuilder.Entity("UPMSF.Server.Data.FormPart1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentAdmissionCapacity")
                        .HasColumnType("int");

                    b.Property<int>("EnhancedAdmissionCapacity")
                        .HasColumnType("int");

                    b.Property<string>("ExecutivePersonNameAndMobile")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HeadNameAndMobile")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NatureOfInstitution")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OtherOngoingTrainings")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RecognitionOrderNumberAndDate")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TotalLandInUpHectare")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("TrainingCenterAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TrainingCenterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("WhereRegistered")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.ToTable("FormPart1s");
                });

            modelBuilder.Entity("UPMSF.Server.Data.FormPart2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<decimal>("CapitalInvestment")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CmoBedCount")
                        .HasColumnType("int");

                    b.Property<string>("CmoRegNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CmoValidity")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentAssetsValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Deposit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FixedAssetsValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HospitalAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("HospitalBedsAtPreviousApplication")
                        .HasColumnType("int");

                    b.Property<string>("HospitalFireRegNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("HospitalFireValidity")
                        .HasColumnType("datetime2");

                    b.Property<string>("HospitalKhasraPlotNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HospitalLandOwnerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("HospitalTotalBeds")
                        .HasColumnType("int");

                    b.Property<int>("HostelBlockBuiltAreaSqft")
                        .HasColumnType("int");

                    b.Property<string>("HostelFireRegNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("HostelFireValidity")
                        .HasColumnType("datetime2");

                    b.Property<string>("HostelKhasraPlotNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InstitutionAccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsHospitalEmpanelledPmjay")
                        .HasColumnType("bit");

                    b.Property<int>("LandAreaSqft")
                        .HasColumnType("int");

                    b.Property<int?>("PcbBedCount")
                        .HasColumnType("int");

                    b.Property<string>("PcbRegNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("PcbValidity")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeachingBlockBuiltAreaSqft")
                        .HasColumnType("int");

                    b.Property<string>("TeachingFireRegNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("TeachingFireValidity")
                        .HasColumnType("datetime2");

                    b.Property<string>("TeachingKhasraPlotNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TeachingLandOwnerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.ToTable("FormPart2s");
                });

            modelBuilder.Entity("UPMSF.Server.Data.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<decimal>("BaseFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GstAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GstPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("UPMSF.Server.Data.Applicant", b =>
                {
                    b.HasOne("UPMSF.Server.Data.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("UPMSF.Server.Data.Application", b =>
                {
                    b.HasOne("UPMSF.Server.Data.Applicant", "Applicant")
                        .WithMany("Applications")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UPMSF.Server.Data.Council", "Council")
                        .WithMany()
                        .HasForeignKey("CouncilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UPMSF.Server.Data.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId");

                    b.Navigation("Applicant");

                    b.Navigation("Council");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("UPMSF.Server.Data.ApplicationDocument", b =>
                {
                    b.HasOne("UPMSF.Server.Data.Application", "Application")
                        .WithMany("Documents")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("UPMSF.Server.Data.FormPart1", b =>
                {
                    b.HasOne("UPMSF.Server.Data.Application", "Application")
                        .WithOne("Part1")
                        .HasForeignKey("UPMSF.Server.Data.FormPart1", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("UPMSF.Server.Data.FormPart2", b =>
                {
                    b.HasOne("UPMSF.Server.Data.Application", "Application")
                        .WithOne("Part2")
                        .HasForeignKey("UPMSF.Server.Data.FormPart2", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("UPMSF.Server.Data.Payment", b =>
                {
                    b.HasOne("UPMSF.Server.Data.Application", "Application")
                        .WithOne("Payment")
                        .HasForeignKey("UPMSF.Server.Data.Payment", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("UPMSF.Server.Data.Applicant", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("UPMSF.Server.Data.Application", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Part1");

                    b.Navigation("Part2");

                    b.Navigation("Payment");
                });
#pragma warning restore 612, 618
        }
    }
}
